---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: workload-f-vpa
spec:
  # recommenders field can be unset when using the default recommender.
  # When using an alternative recommender, the alternative recommender's name
  # can be specified as the following in a list.
  # recommenders: 
  #   - name: 'alternative'
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: workload-f
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 50Mi
        maxAllowed:
          cpu: 4
          memory: 500Mi
        controlledResources: ["cpu", "memory"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-f
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-f
  template:
    metadata:
      labels:
        app: workload-f
        elotl-luna: "true"
    spec:
      containers:
        - name: workload-f
          image: narmidm/k8s-pod-cpu-stressor:latest
          args:
            - "-cpu=0.2"    # low usage, expect VPA to scale-down, bin-select -> bin-pack
            - "-duration=300s"
            - "-forever"
          resources:
            requests:
              cpu: "2"  # bin-select intially
